apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'alb'
    alb.ingress.kubernetes.io/healthcheck-path: '/health'
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
