services:
  gunicorn:
    deploy:
      mode: replicated
      replicas: 2
    restart: always
    build: .
    networks:
      - weather_net

  docker-nginx:
    container_name: WeatherApp_nginx
    restart: always
    image: nginx:latest
    ports:
      - 9090:9090
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - weather_net
    depends_on:
      - gunicorn
  
networks:
  weather_net:
    name: WeatherApp_network
    driver: bridge